### ISSUE TITLE
Proposal: Roadmap to enhancement k8s-authz

### ISSUE THREAD

**Issue by ComradeProgrammer** [casbin/k8s-authz#28]
### 1. Set up basic scaffold
- [ ] 1.1 set up basic project structure
- [ ] 1.2 create CRD resources for casbin model and policy
- [ ] 1.4 generate clients for  CRD resources of casbin model and policy with k8s's official tools
- [ ] 1.3 create adaptor for CRD resources of casbin model and policy
### 2. Impelement rules and policies
- [ ] 2.1 implement the webhook
- [ ] 2.2 implement `Access` and other functions for casbin enforcer
- [ ] 2.3 set up unit tests
- [ ] 2.4 implement rules and policies
### 3. Rewrite documents
- [ ] 3.1 rewrite README.md

**Comment by ComradeProgrammer** [comment]
@sagilio
